# Generated by Django 2.1.4 on 2018-12-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=4000, null=True)),
                ('price', models.CharField(blank=True, max_length=300, null=True)),
                ('w_from', models.TimeField()),
                ('expire_date', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
    ]
